name: Michael Clifford
favicon: null
layout_spectrum: 0.916
typography_spectrum: 0.18871
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.31794498511590064
purpose: []
