name: Michael Clifford
favicon: null
layout_spectrum: 0.7252871082164347
typography_spectrum: 0.257514989702031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6335627816151828
  lightness: 0.11698713316582143
  saturation: 0.6403084313496947
  rhythmicContrast: 0.31794498511590064
purpose: []
